version: "3"
services:
  mongo-express:
    image: mongo-express
    container_name: mongo-express-container
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_AUTH=false
    ports:
      - "8081:8081"
    networks:
      - app-network

  mongodb:
    image: mongo
    container_name: mongodb-container
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
